(require 'migemo)
(setq migemo-command "~/.emacs.d/migemo/cmigemo")
(setq migemo-options '("-q" "--emacs"))
(setq migemo-dictionary "~/.emacs.d/migemo/dict/utf-8/migemo-dict")
(setq migemo-user-dictionary nil)
(setq migemo-coding-system 'utf-8)
(setq migemo-regex-dictionary nil)
(load-library "migemo")
(migemo-init)
